import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
          integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
          crossOrigin="anonymous"
        />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <nav className="pts-navbar">
          <div className="container d-flex justify-content-between align-items-center py-2">
            <Link className="brand" href="/">Poliçe Takip Sistemi</Link>
            <div className="nav-links d-flex gap-2">
              <Link href="/customers">Müşteriler</Link>
              <Link href="/general-information">Genel Bilgiler</Link>
            </div>
          </div>
        </nav>
        <main className="container" style={{ paddingTop: "70px" }}>
          {children}
        </main>

      </body>
    </html>
  );
}
